### ISSUE TITLE
Easy way to get the Nimiq multisig address

### ISSUE THREAD

**Issue by retotrinkler** [Trinkler/agora-swap#18]
Please provide the following information:

### Information about our environment

* OS & Verison
* Browser & Version
* Parity version
* ... other helpful information

**Comment by jsappme** [comment]
I am improving the cli to retrieve it using getExchangeAddress

**Comment by jsappme** [comment]
the asset function depositToMultisig for nimiq returns a deployed address. this is the multisig address that we can use for to display the HTLC account details.

I suggest we switch 3 and 4 in the cli menu, it will make more sense because we use the output of 4) as the input of 3)

(3) Deposit funds to time-locked multisig
(4) Display HTLC account details

instead of 

(3) Display HTLC account details
(4) Deposit funds to time-locked multisig

I will create a PR for this
